name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  VCPKG_BINARY_SOURCES: default

jobs:
  build:
    env:
      BUILD_TYPE: Debug

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Cache Vcpkg packages
      env:
        cache-name: silicon-vcpkg
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
        path: |
          /home/runner/.cache/vcpkg/archives
          ./vcpkg_installed
      
    - name: Setup Script
      run: pip3 install distro requests && python3 ./utils/setup.py --install-vulkan

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSKIP_ENGINE_TESTS=ON

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{matrix.build-type}}
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: CMake Test Logs
        path: /home/runner/work/silicon/silicon/build/Testing/Temporary/LastTest.log
